---
- name: Install AWS CLI
  homebrew:
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - awscli

- name: Create .aws folder 
  file: path="~/.aws" state=directory mode=0755

- name: Copy AWS credentials file from Config
  copy: >
    src="~/Dropbox/Config/aws/{{item}}"
    dest="~/.aws/{{item}}"
    mode=0444
  with_items:
    - credentials

