---
- name: Create .bin folder
  file: path="~/.bin" state="directory"

- name: Install base development packages
  homebrew: 
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - coreutils
    - imagemagick  
    - wget
    - selecta
    - ctags
    - pv
    - ack
    - tree
    - jq
    - the_silver_searcher
    - cmake
    - autoconf
    - gettext
    - libevent
    - bfg
    - heroku-toolbelt
    - plantuml
    - hh
    - docker
    - docker-machine
    - htop-osx
    - mobile-shell

- name: Install base development applications
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - virtualbox
    - iterm2
    - vagrant
    - dash
    - lighttable
    - coderunner

- name: Copy ack configuration file
  copy: >
    src=ackrc
    dest=~/.ackrc
    mode=644

- include: copy_ssh.yml
- include: aws-cli.yml

- include: exercism.yml

- name: Install challenges-cli
  pip:
    name: challenge-cli
