---
- name: Install base OS X packages
  homebrew:
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - ffmpeg
    - qt
    - youtube-dl

- name: Install base macOS apps via homebrew
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - 1password
    - alfred
    - bettertouchtool
    - calibre
    - controlplane
    - crashplan
    - flux
    - hazel
    - keyboard-maestro
    - launchrocket
    - mactex
    - omnifocus
    - omnipresence
    - path-finder
    - qlcolorcode
    - qlmarkdown
    - quicklook-json
    - rescuetime
    - skitch
    - skype
    - transmit
    - utorrent

- name: Install base macOS apps via pip
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - pockyt

- name: Remap Caps Lock to Control
  command: osascript topics/base_osx/files/remap_capslock_to_ctrl.scpt

#- include: move_downloads.yml
  #tags:
    #- debug

