---
- name: Install base OS X packages
  homebrew:
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - qt
    - ffmpeg

- name: Install base OS X apps
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items:
    - bettertouchtool
    - skype
    - transmit
    - flux
    - textexpander
    - skitch
    - alfred
    - launchrocket
    - controlplane
    - calibre
    - omnifocus
    - crashplan
    - keyboard-maestro
    - mactex
    - utorrent
    - hazel
    - qlcolorcode
    - qlmarkdown
    - quicklook-json
    - omnipresence
    - path-finder

- name: Remap Caps Lock to Control
  command: osascript roles/base_osx/files/remap_capslock_to_ctrl.scpt

#- include: move_downloads.yml
  #tags:
    #- debug

