---

- name: Expand save panel by default
  osx_defaults:
    key: NSNavPanelExpandedStateForSaveMode
    type: bool 
    value: true

- name: Don’t display the annoying prompt when quitting iTerm
  osx_defaults:
    domain: com.googlecode.iterm2 
    key: PromptOnQuit 
    type: bool 
    value: false
