---
- name: Download JDK
  command: >
    chdir={{ downloads_directory }}
    curl -L --cookie "gpw_e24=http%3A%2F%2Fwww.oracle.com%2Ftechnetwork%2Fjava%2Fjavase%2Fdownloads%2Fjdk8-downloads-2133155.html; oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u91-b14/jdk-8u91-macosx-x64.dmg -z jdk-8u91-macosx-x64.dmg -o jdk-8u91-macosx-x64.dmg
    creates={{ downloads_directory }}/jdk-8u91-macosx-x64.dmg
- name: Mount JDK image
  command: >
    chdir={{ downloads_directory }}
    hdiutil attach jdk-8u91-macosx-x64.dmg

- shell: java -version 2>&1
  register: java_version

- name: Install JDK
  command: >
    installer -package /Volumes/JDK\ 8\ Update\ 91/JDK\ 8\ Update\ 91.pkg -target /
  become: yes
  when: java_version.stdout.find('java version "1.8.0_91"') == -1

- name: Unmount JDK image
  command: hdiutil detach /Volumes/JDK\ 8\ Update\ 91

- name: Create Java-specific zsh config subfolder
  file: path=~/.zsh/java state=directory 

- name: Copy Java-specific config file
  copy: >
    src=java.zsh
    dest=~/.zsh/java/java.zsh
