---
- name: Install base development packages
  homebrew: 
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - tmux  
    - reattach-to-user-namespace

- name: Copy .tmux configuration file
  copy: >
    src=tmux.conf
    dest=~/.tmux.conf
    mode=644

- name: Copy code.sh script
  copy: >
    src=code.sh
    dest=~/.bin/code
    mode=755

