---

- name: Install data science pre-req apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - xquartz

- name: Tap homebrew/science repository
  homebrew_tap:
    tap: homebrew/science
    state: present

- name: Install data science packages
  homebrew: 
    name: "{{item}}"
    update_homebrew: yes
    upgrade_all: yes
    state: latest
  with_items:
    - r  
    - octave
    - gnuplot

- name: Install data science apps
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - weka
    - rstudio
    - pineapple
